{% set name = "pennylane" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane/archive/v{{ version }}.tar.gz
  sha256: b2d37227e098d4fc58556a07ba76eb5e2cefef52bff5605b465a01e5acb6941c

build:
  entry_points:
    - pl-device-test=pennylane.devices.tests:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - appdirs
    - autograd
    - autoray
    - cachetools
    - networkx
    - numpy
    - pennylane-lightning >=0.23
    - python >=3.7
    - retworkx
    - scipy
    - semantic_version ==2.6
    - toml

test:
  imports:
    - pennylane
  commands:
    - pip check
    - pl-device-test --help
  requires:
    - pip
    - pytest

about:
  home: https://github.com/PennyLaneAI/pennylane
  summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
  license: Apache-2.0 AND MIT
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vincentmr
    - BastianZim
